import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home({title}) {
  return (
    <>
      <Head>
        <title>Events App</title>
        {title}
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <nav>
          <img />
          <a href='/'>Home </a>
          <a href='/events'> Events</a>
          <a href='/about-us'> About Us</a>
        </nav>
      </header>

      <main className={styles.main}>
        <a href='/events/london'>
          {' '}
          <img />
        </a>
        <div>
          <h2>Events in London</h2>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam quae voluptas, quod voluptates quibusdam voluptatibus.

          </p>
        </div>

        <a href='/events/sanfran'>
          {' '}
          <img />
        </a>
        <div>
          <h2>Events in San Francisco</h2>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam quae voluptas, quod voluptates quibusdam voluptatibus.

          </p>
        </div>

        <a href='/events/barcelona'>
          {' '}
          <img />
        </a>
        <div>
          <h2>Events in Barcelona</h2>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam quae voluptas, quod voluptates quibusdam voluptatibus.

          </p>
        </div>



      </main>
      
      <footer className={styles.footer}>

        <p> © 2023 Courtney Codes - A Next.js Project</p>
      </footer>
     
    </>
  );
}


export async function getServerSideProps() {
  // returns an asynchronous function so must add await
  //gets from server side
  const { events_categories } = await import('data/data.json');
  console.log(events_categories);

  // // example of external api fetch
  // const res = await fetch('https://jsonplaceholder.typicode.com/users');
  // const data= await res.json();


  return {
    props: {
      title: 'Hello everyone'
    },
  };
}
// ^ needs to be exported as a stand alone function (runs first)