import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home({data}) {
  return (
    <>
      <Head>
        <title>Events App</title>
        
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <nav>
          <img />
          <a href='/'>Home </a>
          <a href='/events/'> Events</a>
          <a href='/about-us'> About Us</a>
        </nav>
      </header>

      <main className={styles.main}>
        {data.map((ev) => (
        <a key={ev.id} href={`/events/${ev.id}`}>
          <Image width={200} height={100} alt={ev.title} src={ev.image} /> <h2> {ev.title} </h2> <p>
            {ev.description} </p>
            </a>
            ))}

       


    
      </main>
      
      <footer className={styles.footer}>

        <p> © 2023 Courtney Codes - A Next.js Project</p>
      </footer>
     
    </>
  );
}


export async function getServerSideProps() {
  // returns an asynchronous function so must add await
  //gets from server side
  const { events_categories } = await import('data/data.json');
  console.log(events_categories);

  // // example of external api fetch
  // const res = await fetch('https://jsonplaceholder.typicode.com/users');
  // const data= await res.json();


  return {
    props: {
      data: events_categories,
    },
  };
}
// ^ needs to be exported as a stand alone function (runs first)